package com.huateng.sumer.sandbox.web.db.model;

import java.io.Serializable;
import java.util.Date;

public class TblAdmUser extends TblAdmUserKey implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_adm_user.password
     *
     * @ibatorgenerated
     */
    private String password;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_adm_user.name
     *
     * @ibatorgenerated
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_adm_user.expire
     *
     * @ibatorgenerated
     */
    private Date expire;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_adm_user.enabled
     *
     * @ibatorgenerated
     */
    private Boolean enabled;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_adm_user.organization
     *
     * @ibatorgenerated
     */
    private String organization;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_adm_user.group_id
     *
     * @ibatorgenerated
     */
    private Integer groupId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table tbl_adm_user
     *
     * @ibatorgenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_adm_user.password
     *
     * @return the value of tbl_adm_user.password
     *
     * @ibatorgenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_adm_user.password
     *
     * @param password the value for tbl_adm_user.password
     *
     * @ibatorgenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_adm_user.name
     *
     * @return the value of tbl_adm_user.name
     *
     * @ibatorgenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_adm_user.name
     *
     * @param name the value for tbl_adm_user.name
     *
     * @ibatorgenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_adm_user.expire
     *
     * @return the value of tbl_adm_user.expire
     *
     * @ibatorgenerated
     */
    public Date getExpire() {
        return expire;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_adm_user.expire
     *
     * @param expire the value for tbl_adm_user.expire
     *
     * @ibatorgenerated
     */
    public void setExpire(Date expire) {
        this.expire = expire;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_adm_user.enabled
     *
     * @return the value of tbl_adm_user.enabled
     *
     * @ibatorgenerated
     */
    public Boolean getEnabled() {
        return enabled;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_adm_user.enabled
     *
     * @param enabled the value for tbl_adm_user.enabled
     *
     * @ibatorgenerated
     */
    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_adm_user.organization
     *
     * @return the value of tbl_adm_user.organization
     *
     * @ibatorgenerated
     */
    public String getOrganization() {
        return organization;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_adm_user.organization
     *
     * @param organization the value for tbl_adm_user.organization
     *
     * @ibatorgenerated
     */
    public void setOrganization(String organization) {
        this.organization = organization == null ? null : organization.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_adm_user.group_id
     *
     * @return the value of tbl_adm_user.group_id
     *
     * @ibatorgenerated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_adm_user.group_id
     *
     * @param groupId the value for tbl_adm_user.group_id
     *
     * @ibatorgenerated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_user
     *
     * @ibatorgenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (!(that instanceof TblAdmUser)) {
            return false;
        }
        TblAdmUser other = (TblAdmUser) that;
        return this.getUserId() == null ? other == null : this.getUserId().equals(other.getUserId())
            && this.getPassword() == null ? other == null : this.getPassword().equals(other.getPassword())
            && this.getName() == null ? other == null : this.getName().equals(other.getName())
            && this.getExpire() == null ? other == null : this.getExpire().equals(other.getExpire())
            && this.getEnabled() == null ? other == null : this.getEnabled().equals(other.getEnabled())
            && this.getOrganization() == null ? other == null : this.getOrganization().equals(other.getOrganization())
            && this.getGroupId() == null ? other == null : this.getGroupId().equals(other.getGroupId());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_user
     *
     * @ibatorgenerated
     */
    @Override
    public int hashCode() {
        int hash = 23;
        if (getUserId() != null) {
            hash *= getUserId().hashCode();
        }
        if (getPassword() != null) {
            hash *= getPassword().hashCode();
        }
        if (getName() != null) {
            hash *= getName().hashCode();
        }
        if (getExpire() != null) {
            hash *= getExpire().hashCode();
        }
        if (getEnabled() != null) {
            hash *= getEnabled().hashCode();
        }
        if (getOrganization() != null) {
            hash *= getOrganization().hashCode();
        }
        if (getGroupId() != null) {
            hash *= getGroupId().hashCode();
        }
        return hash;
    }
}