package com.huateng.sumer.sandbox.web.db.model;

import java.io.Serializable;

public class TblAdmUserKey implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_adm_user.user_id
     *
     * @ibatorgenerated
     */
    private String userId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table tbl_adm_user
     *
     * @ibatorgenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_adm_user.user_id
     *
     * @return the value of tbl_adm_user.user_id
     *
     * @ibatorgenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_adm_user.user_id
     *
     * @param userId the value for tbl_adm_user.user_id
     *
     * @ibatorgenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_user
     *
     * @ibatorgenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (!(that instanceof TblAdmUserKey)) {
            return false;
        }
        TblAdmUserKey other = (TblAdmUserKey) that;
        return this.getUserId() == null ? other == null : this.getUserId().equals(other.getUserId());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_user
     *
     * @ibatorgenerated
     */
    @Override
    public int hashCode() {
        int hash = 23;
        if (getUserId() != null) {
            hash *= getUserId().hashCode();
        }
        return hash;
    }
}