package com.huateng.sumer.sandbox.web.db.dao;

import com.huateng.sumer.sandbox.web.db.model.TblAdmGroup;
import com.huateng.sumer.sandbox.web.db.model.TblAdmGroupExample;
import com.huateng.sumer.sandbox.web.db.model.TblAdmGroupKey;
import com.ibatis.sqlmap.client.SqlMapClient;
import java.sql.SQLException;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

@Repository
public class TblAdmGroupDAOImpl implements TblAdmGroupDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table tbl_adm_group
     *
     * @ibatorgenerated
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group
     *
     * @ibatorgenerated
     */
    @Autowired
    public TblAdmGroupDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group
     *
     * @ibatorgenerated
     */
    public int countByExample(TblAdmGroupExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("tbl_adm_group.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group
     *
     * @ibatorgenerated
     */
    public int deleteByExample(TblAdmGroupExample example) throws SQLException {
        int rows = sqlMapClient.delete("tbl_adm_group.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(TblAdmGroupKey key) throws SQLException {
        int rows = sqlMapClient.delete("tbl_adm_group.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group
     *
     * @ibatorgenerated
     */
    public void insert(TblAdmGroup record) throws SQLException {
        sqlMapClient.insert("tbl_adm_group.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group
     *
     * @ibatorgenerated
     */
    public void insertSelective(TblAdmGroup record) throws SQLException {
        sqlMapClient.insert("tbl_adm_group.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<TblAdmGroup> selectByExample(TblAdmGroupExample example) throws SQLException {
        List<TblAdmGroup> list = sqlMapClient.queryForList("tbl_adm_group.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group
     *
     * @ibatorgenerated
     */
    public TblAdmGroup selectByPrimaryKey(TblAdmGroupKey key) throws SQLException {
        TblAdmGroup record = (TblAdmGroup) sqlMapClient.queryForObject("tbl_adm_group.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(TblAdmGroup record, TblAdmGroupExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("tbl_adm_group.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group
     *
     * @ibatorgenerated
     */
    public int updateByExample(TblAdmGroup record, TblAdmGroupExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("tbl_adm_group.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(TblAdmGroup record) throws SQLException {
        int rows = sqlMapClient.update("tbl_adm_group.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(TblAdmGroup record) throws SQLException {
        int rows = sqlMapClient.update("tbl_adm_group.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tbl_adm_group
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends TblAdmGroupExample {
        private Object record;

        public UpdateByExampleParms(Object record, TblAdmGroupExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}