package com.huateng.sumer.sandbox.web.db.dao;

import com.huateng.sumer.sandbox.web.db.model.TblAdmGroupAuthorities;
import com.huateng.sumer.sandbox.web.db.model.TblAdmGroupAuthoritiesExample;
import com.ibatis.sqlmap.client.SqlMapClient;
import java.sql.SQLException;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

@Repository
public class TblAdmGroupAuthoritiesDAOImpl implements TblAdmGroupAuthoritiesDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table tbl_adm_group_authorities
     *
     * @ibatorgenerated
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group_authorities
     *
     * @ibatorgenerated
     */
    @Autowired
    public TblAdmGroupAuthoritiesDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group_authorities
     *
     * @ibatorgenerated
     */
    public int countByExample(TblAdmGroupAuthoritiesExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("tbl_adm_group_authorities.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group_authorities
     *
     * @ibatorgenerated
     */
    public int deleteByExample(TblAdmGroupAuthoritiesExample example) throws SQLException {
        int rows = sqlMapClient.delete("tbl_adm_group_authorities.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group_authorities
     *
     * @ibatorgenerated
     */
    public void insert(TblAdmGroupAuthorities record) throws SQLException {
        sqlMapClient.insert("tbl_adm_group_authorities.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group_authorities
     *
     * @ibatorgenerated
     */
    public void insertSelective(TblAdmGroupAuthorities record) throws SQLException {
        sqlMapClient.insert("tbl_adm_group_authorities.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group_authorities
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<TblAdmGroupAuthorities> selectByExample(TblAdmGroupAuthoritiesExample example) throws SQLException {
        List<TblAdmGroupAuthorities> list = sqlMapClient.queryForList("tbl_adm_group_authorities.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group_authorities
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(TblAdmGroupAuthorities record, TblAdmGroupAuthoritiesExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("tbl_adm_group_authorities.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group_authorities
     *
     * @ibatorgenerated
     */
    public int updateByExample(TblAdmGroupAuthorities record, TblAdmGroupAuthoritiesExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("tbl_adm_group_authorities.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tbl_adm_group_authorities
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends TblAdmGroupAuthoritiesExample {
        private Object record;

        public UpdateByExampleParms(Object record, TblAdmGroupAuthoritiesExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}