package com.huateng.sumer.sandbox.web.db.dao;

import com.huateng.sumer.sandbox.web.db.model.TblAdmGroupAuthorities;
import com.huateng.sumer.sandbox.web.db.model.TblAdmGroupAuthoritiesExample;
import java.sql.SQLException;
import java.util.List;

public interface TblAdmGroupAuthoritiesDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group_authorities
     *
     * @ibatorgenerated
     */
    int countByExample(TblAdmGroupAuthoritiesExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group_authorities
     *
     * @ibatorgenerated
     */
    int deleteByExample(TblAdmGroupAuthoritiesExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group_authorities
     *
     * @ibatorgenerated
     */
    void insert(TblAdmGroupAuthorities record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group_authorities
     *
     * @ibatorgenerated
     */
    void insertSelective(TblAdmGroupAuthorities record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group_authorities
     *
     * @ibatorgenerated
     */
    List<TblAdmGroupAuthorities> selectByExample(TblAdmGroupAuthoritiesExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group_authorities
     *
     * @ibatorgenerated
     */
    int updateByExampleSelective(TblAdmGroupAuthorities record, TblAdmGroupAuthoritiesExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group_authorities
     *
     * @ibatorgenerated
     */
    int updateByExample(TblAdmGroupAuthorities record, TblAdmGroupAuthoritiesExample example) throws SQLException;
}