package com.huateng.sumer.sandbox.web.db.dao;

import com.huateng.sumer.sandbox.web.db.model.TblAdmUser;
import com.huateng.sumer.sandbox.web.db.model.TblAdmUserExample;
import com.huateng.sumer.sandbox.web.db.model.TblAdmUserKey;
import java.sql.SQLException;
import java.util.List;

public interface TblAdmUserDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_user
     *
     * @ibatorgenerated
     */
    int countByExample(TblAdmUserExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_user
     *
     * @ibatorgenerated
     */
    int deleteByExample(TblAdmUserExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_user
     *
     * @ibatorgenerated
     */
    int deleteByPrimaryKey(TblAdmUserKey key) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_user
     *
     * @ibatorgenerated
     */
    void insert(TblAdmUser record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_user
     *
     * @ibatorgenerated
     */
    void insertSelective(TblAdmUser record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_user
     *
     * @ibatorgenerated
     */
    List<TblAdmUser> selectByExample(TblAdmUserExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_user
     *
     * @ibatorgenerated
     */
    TblAdmUser selectByPrimaryKey(TblAdmUserKey key) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_user
     *
     * @ibatorgenerated
     */
    int updateByExampleSelective(TblAdmUser record, TblAdmUserExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_user
     *
     * @ibatorgenerated
     */
    int updateByExample(TblAdmUser record, TblAdmUserExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_user
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKeySelective(TblAdmUser record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_user
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKey(TblAdmUser record) throws SQLException;
}