package com.huateng.sumer.sandbox.web.db.dao;

import com.huateng.sumer.sandbox.web.db.model.TblAdmGroup;
import com.huateng.sumer.sandbox.web.db.model.TblAdmGroupExample;
import com.huateng.sumer.sandbox.web.db.model.TblAdmGroupKey;
import java.sql.SQLException;
import java.util.List;

public interface TblAdmGroupDAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group
     *
     * @ibatorgenerated
     */
    int countByExample(TblAdmGroupExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group
     *
     * @ibatorgenerated
     */
    int deleteByExample(TblAdmGroupExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group
     *
     * @ibatorgenerated
     */
    int deleteByPrimaryKey(TblAdmGroupKey key) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group
     *
     * @ibatorgenerated
     */
    void insert(TblAdmGroup record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group
     *
     * @ibatorgenerated
     */
    void insertSelective(TblAdmGroup record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group
     *
     * @ibatorgenerated
     */
    List<TblAdmGroup> selectByExample(TblAdmGroupExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group
     *
     * @ibatorgenerated
     */
    TblAdmGroup selectByPrimaryKey(TblAdmGroupKey key) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group
     *
     * @ibatorgenerated
     */
    int updateByExampleSelective(TblAdmGroup record, TblAdmGroupExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group
     *
     * @ibatorgenerated
     */
    int updateByExample(TblAdmGroup record, TblAdmGroupExample example) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKeySelective(TblAdmGroup record) throws SQLException;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group
     *
     * @ibatorgenerated
     */
    int updateByPrimaryKey(TblAdmGroup record) throws SQLException;
}