package com.huateng.sumer.sandbox.web.db.dao;

import com.huateng.sumer.sandbox.web.db.model.TblAdmUser;
import com.huateng.sumer.sandbox.web.db.model.TblAdmUserExample;
import com.huateng.sumer.sandbox.web.db.model.TblAdmUserKey;
import com.ibatis.sqlmap.client.SqlMapClient;
import java.sql.SQLException;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;

@Repository
public class TblAdmUserDAOImpl implements TblAdmUserDAO {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table tbl_adm_user
     *
     * @ibatorgenerated
     */
    private SqlMapClient sqlMapClient;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_user
     *
     * @ibatorgenerated
     */
    @Autowired
    public TblAdmUserDAOImpl(SqlMapClient sqlMapClient) {
        super();
        this.sqlMapClient = sqlMapClient;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_user
     *
     * @ibatorgenerated
     */
    public int countByExample(TblAdmUserExample example) throws SQLException {
        Integer count = (Integer)  sqlMapClient.queryForObject("tbl_adm_user.ibatorgenerated_countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_user
     *
     * @ibatorgenerated
     */
    public int deleteByExample(TblAdmUserExample example) throws SQLException {
        int rows = sqlMapClient.delete("tbl_adm_user.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_user
     *
     * @ibatorgenerated
     */
    public int deleteByPrimaryKey(TblAdmUserKey key) throws SQLException {
        int rows = sqlMapClient.delete("tbl_adm_user.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_user
     *
     * @ibatorgenerated
     */
    public void insert(TblAdmUser record) throws SQLException {
        sqlMapClient.insert("tbl_adm_user.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_user
     *
     * @ibatorgenerated
     */
    public void insertSelective(TblAdmUser record) throws SQLException {
        sqlMapClient.insert("tbl_adm_user.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_user
     *
     * @ibatorgenerated
     */
    @SuppressWarnings("unchecked")
    public List<TblAdmUser> selectByExample(TblAdmUserExample example) throws SQLException {
        List<TblAdmUser> list = sqlMapClient.queryForList("tbl_adm_user.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_user
     *
     * @ibatorgenerated
     */
    public TblAdmUser selectByPrimaryKey(TblAdmUserKey key) throws SQLException {
        TblAdmUser record = (TblAdmUser) sqlMapClient.queryForObject("tbl_adm_user.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_user
     *
     * @ibatorgenerated
     */
    public int updateByExampleSelective(TblAdmUser record, TblAdmUserExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("tbl_adm_user.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_user
     *
     * @ibatorgenerated
     */
    public int updateByExample(TblAdmUser record, TblAdmUserExample example) throws SQLException {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = sqlMapClient.update("tbl_adm_user.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_user
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKeySelective(TblAdmUser record) throws SQLException {
        int rows = sqlMapClient.update("tbl_adm_user.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_user
     *
     * @ibatorgenerated
     */
    public int updateByPrimaryKey(TblAdmUser record) throws SQLException {
        int rows = sqlMapClient.update("tbl_adm_user.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table tbl_adm_user
     *
     * @ibatorgenerated
     */
    private static class UpdateByExampleParms extends TblAdmUserExample {
        private Object record;

        public UpdateByExampleParms(Object record, TblAdmUserExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}