package com.huateng.sumer.sandbox.web.db.model;

import java.io.Serializable;

public class TblAdmGroupKey implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_adm_group.group_id
     *
     * @ibatorgenerated
     */
    private Integer groupId;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table tbl_adm_group
     *
     * @ibatorgenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_adm_group.group_id
     *
     * @return the value of tbl_adm_group.group_id
     *
     * @ibatorgenerated
     */
    public Integer getGroupId() {
        return groupId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_adm_group.group_id
     *
     * @param groupId the value for tbl_adm_group.group_id
     *
     * @ibatorgenerated
     */
    public void setGroupId(Integer groupId) {
        this.groupId = groupId;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group
     *
     * @ibatorgenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (!(that instanceof TblAdmGroupKey)) {
            return false;
        }
        TblAdmGroupKey other = (TblAdmGroupKey) that;
        return this.getGroupId() == null ? other == null : this.getGroupId().equals(other.getGroupId());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group
     *
     * @ibatorgenerated
     */
    @Override
    public int hashCode() {
        int hash = 23;
        if (getGroupId() != null) {
            hash *= getGroupId().hashCode();
        }
        return hash;
    }
}