package com.huateng.sumer.sandbox.web.db.model;

import java.io.Serializable;

public class TblAdmGroup extends TblAdmGroupKey implements Serializable {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column tbl_adm_group.name
     *
     * @ibatorgenerated
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database table tbl_adm_group
     *
     * @ibatorgenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column tbl_adm_group.name
     *
     * @return the value of tbl_adm_group.name
     *
     * @ibatorgenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column tbl_adm_group.name
     *
     * @param name the value for tbl_adm_group.name
     *
     * @ibatorgenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group
     *
     * @ibatorgenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (!(that instanceof TblAdmGroup)) {
            return false;
        }
        TblAdmGroup other = (TblAdmGroup) that;
        return this.getGroupId() == null ? other == null : this.getGroupId().equals(other.getGroupId())
            && this.getName() == null ? other == null : this.getName().equals(other.getName());
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table tbl_adm_group
     *
     * @ibatorgenerated
     */
    @Override
    public int hashCode() {
        int hash = 23;
        if (getGroupId() != null) {
            hash *= getGroupId().hashCode();
        }
        if (getName() != null) {
            hash *= getName().hashCode();
        }
        return hash;
    }
}